#!/bin/bash
btcli regen_coldkeypub --ss58 5DxyxnZM6aqJT4HQAogmf3esE5fFvsokBjpZugg3HD1zyuAs --wallet.name alice
btcli regen_hotkey --wallet.name alice --wallet.hotkey 0 --mnemonic rescue trip video hold maximum airport drama road giraffe science chapter answer
btcli regen_hotkey --wallet.name alice --wallet.hotkey 1 --mnemonic stool link heart swallow dilemma wild design kingdom multiply own detect rack
btcli regen_hotkey --wallet.name alice --wallet.hotkey 2 --mnemonic word churn topic catalog parent fury sauce van drive diamond crane absurd
btcli regen_hotkey --wallet.name alice --wallet.hotkey 3 --mnemonic reform current same mind scene quiz boost day donkey scissors sunny track
btcli regen_hotkey --wallet.name alice --wallet.hotkey 4 --mnemonic little grocery call ask immune stage whale tortoise shed brother author pudding
btcli regen_hotkey --wallet.name alice --wallet.hotkey 5 --mnemonic author answer left apology gossip picture sphere guitar city glare joy advance
btcli regen_hotkey --wallet.name alice --wallet.hotkey 6 --mnemonic opera version hold valley defy owner tissue neck must tribe course rookie
btcli regen_hotkey --wallet.name alice --wallet.hotkey 7 --mnemonic earth common sample omit book garbage pepper october small resemble attack traffic
btcli regen_hotkey --wallet.name alice --wallet.hotkey 8 --mnemonic congress barely citizen razor sound romance curtain original gaze rookie shift comic
btcli regen_hotkey --wallet.name alice --wallet.hotkey 9 --mnemonic wheat release sense sketch loyal rely pave gospel river asthma scrap build
btcli regen_hotkey --wallet.name alice --wallet.hotkey 10 --mnemonic frequent alert near chaos tail owner weird diesel kid begin phrase ripple
btcli regen_hotkey --wallet.name alice --wallet.hotkey 11 --mnemonic craft oblige orient more sun private wear decline rookie craft damage alarm
btcli regen_hotkey --wallet.name alice --wallet.hotkey 12 --mnemonic else space plug error occur happy visual palace sustain penalty crumble wrestle
btcli regen_hotkey --wallet.name alice --wallet.hotkey 13 --mnemonic dumb poem ostrich portion lend crawl slam tag hamster valley tissue reject
btcli regen_hotkey --wallet.name alice --wallet.hotkey 14 --mnemonic floor raccoon enable divert satisfy destroy round super jealous recycle shrimp tuna
btcli regen_hotkey --wallet.name alice --wallet.hotkey 15 --mnemonic heart latin slow source bulk legend chase announce mystery right glimpse aware
btcli regen_hotkey --wallet.name alice --wallet.hotkey 16 --mnemonic orchard dinosaur report nephew water area waste hen violin reject crisp flush
btcli regen_hotkey --wallet.name alice --wallet.hotkey 17 --mnemonic cluster host choice gold merry skill wisdom birth limit stand empty curtain
btcli regen_hotkey --wallet.name alice --wallet.hotkey 18 --mnemonic ketchup firm trigger subject absurd erupt bounce enlist add mirror giraffe loop
btcli regen_hotkey --wallet.name alice --wallet.hotkey 19 --mnemonic mutual hip document fluid gasp upset heavy valid decrease dance drastic burden
btcli regen_hotkey --wallet.name alice --wallet.hotkey 20 --mnemonic hire rely title lock crucial check elevator spread mask parade route private
btcli regen_hotkey --wallet.name alice --wallet.hotkey 21 --mnemonic false decide guide nerve voice lock dutch heart dove uncle crisp adapt
btcli regen_hotkey --wallet.name alice --wallet.hotkey 22 --mnemonic length collect critic advance aware again vault clay pepper sweet rug penalty
btcli regen_hotkey --wallet.name alice --wallet.hotkey 23 --mnemonic run tenant ghost merry warfare tongue best armed ticket pool scout holiday
btcli regen_hotkey --wallet.name alice --wallet.hotkey 24 --mnemonic zebra enact march weasel shy piece alert wet comfort garden tooth stairs
btcli regen_hotkey --wallet.name alice --wallet.hotkey 25 --mnemonic royal extend dash dawn carpet misery feed attitude nothing arena profit kangaroo
btcli regen_hotkey --wallet.name alice --wallet.hotkey 26 --mnemonic canyon length myth velvet own family solve enjoy mutual moment metal office
btcli regen_hotkey --wallet.name alice --wallet.hotkey 27 --mnemonic object grant hair lawsuit result junior protect voice guard cheap urge alien
btcli regen_hotkey --wallet.name alice --wallet.hotkey 28 --mnemonic disagree fossil merry damp jewel hole bench rent stumble fly sibling gasp
btcli regen_hotkey --wallet.name alice --wallet.hotkey 29 --mnemonic observe welcome any problem dance update senior world hero cousin curious mail
btcli regen_hotkey --wallet.name alice --wallet.hotkey 30 --mnemonic bundle theory pulp word journey cook desert sadness sense useless noble defy
btcli regen_hotkey --wallet.name alice --wallet.hotkey 31 --mnemonic mango clarify lucky someone solid net lawsuit express found siege same fever
btcli regen_hotkey --wallet.name alice --wallet.hotkey 32 --mnemonic differ wine enjoy chest parent belt common buffalo jar animal dog curve
btcli regen_hotkey --wallet.name alice --wallet.hotkey 33 --mnemonic minimum success parade weasel huge subject give renew logic burst coyote husband
btcli regen_hotkey --wallet.name alice --wallet.hotkey 34 --mnemonic ladder all settle easily utility hurt chat teach suit typical sponsor rug
btcli regen_hotkey --wallet.name alice --wallet.hotkey 35 --mnemonic diary valley salt rally outdoor citizen heavy more oil nut music owner
btcli regen_hotkey --wallet.name alice --wallet.hotkey 36 --mnemonic loud bench online other churn stool burger drastic heart yard broccoli wash
btcli regen_hotkey --wallet.name alice --wallet.hotkey 37 --mnemonic decorate gas alter scene expose mesh custom insect volume farm swarm fan
btcli regen_hotkey --wallet.name alice --wallet.hotkey 38 --mnemonic lunch trap odor jelly soap recycle glass trick skin pistol deposit degree
btcli regen_hotkey --wallet.name alice --wallet.hotkey 39 --mnemonic humble pyramid orbit layer rely ask glue season size door diesel paddle
btcli regen_hotkey --wallet.name alice --wallet.hotkey 40 --mnemonic crisp neither hole gesture fiber bus critic silk essence hope index hover
btcli regen_hotkey --wallet.name alice --wallet.hotkey 41 --mnemonic tuna slight tongue panel bone account broccoli team easy barrel urge credit
btcli regen_hotkey --wallet.name alice --wallet.hotkey 42 --mnemonic ready law alley select candy wage suffer aspect heart chase tired disorder
btcli regen_hotkey --wallet.name alice --wallet.hotkey 43 --mnemonic resist mixture crane duck know item rice strike neither legend accident any
btcli regen_hotkey --wallet.name alice --wallet.hotkey 44 --mnemonic elbow input math pattern educate piece tumble universe chimney exit one october
btcli regen_hotkey --wallet.name alice --wallet.hotkey 45 --mnemonic trick comic leaf betray broom tide father theory brain anxiety casual garlic
btcli regen_hotkey --wallet.name alice --wallet.hotkey 46 --mnemonic elevator enroll harsh smooth sense swear future traffic glue recycle vintage clip
btcli regen_hotkey --wallet.name alice --wallet.hotkey 47 --mnemonic room abandon ostrich symptom nuclear goddess erode total mail search own resist
btcli regen_hotkey --wallet.name alice --wallet.hotkey 48 --mnemonic salad foil approve labor this potato aspect weekend wagon panther ranch age
btcli regen_hotkey --wallet.name alice --wallet.hotkey 49 --mnemonic nephew cushion legend stage swap parrot cotton mushroom diagram couch sheriff dutch
btcli regen_hotkey --wallet.name alice --wallet.hotkey 50 --mnemonic guitar urban hint nuclear net adjust list aunt carry jar pigeon hybrid
btcli regen_hotkey --wallet.name alice --wallet.hotkey 51 --mnemonic race audit riot provide concert diagram swear thing chase december stumble marble
btcli regen_hotkey --wallet.name alice --wallet.hotkey 52 --mnemonic fine bind burst nice later entire deer dwarf scrub reform fabric damage
btcli regen_hotkey --wallet.name alice --wallet.hotkey 53 --mnemonic wool net winter dragon tank item pudding awkward vague soccer never riot
btcli regen_hotkey --wallet.name alice --wallet.hotkey 54 --mnemonic trophy luxury list milk syrup one area entry media peasant hockey scale
btcli regen_hotkey --wallet.name alice --wallet.hotkey 55 --mnemonic feel fancy hen drop recipe absurd refuse either torch phone can among
btcli regen_hotkey --wallet.name alice --wallet.hotkey 56 --mnemonic spin unit public result pig own weather warm shiver measure warfare square
btcli regen_hotkey --wallet.name alice --wallet.hotkey 57 --mnemonic disorder pave popular game furnace apart nature omit vicious harbor helmet just
btcli regen_hotkey --wallet.name alice --wallet.hotkey 58 --mnemonic insect coyote tip include razor powder photo mind vintage point burger fire
btcli regen_hotkey --wallet.name alice --wallet.hotkey 59 --mnemonic dynamic leopard section attend prevent spray detect foot close time already emotion
btcli regen_hotkey --wallet.name alice --wallet.hotkey 60 --mnemonic poem chair camera help curious dog federal invest height jelly fortune great
btcli regen_hotkey --wallet.name alice --wallet.hotkey 61 --mnemonic trend output type chaos rescue point habit earth region brick either reduce
btcli regen_hotkey --wallet.name alice --wallet.hotkey 62 --mnemonic found supreme youth come goddess put supply item spatial earth term gloom
btcli regen_hotkey --wallet.name alice --wallet.hotkey 63 --mnemonic pumpkin modify powder hour east tank wise amazing curtain danger predict coconut
btcli regen_hotkey --wallet.name alice --wallet.hotkey 64 --mnemonic patrol cargo ski love practice dirt quality benefit blouse fork soccer old
btcli regen_hotkey --wallet.name alice --wallet.hotkey 65 --mnemonic bomb cake inner doctor slight asthma anxiety consider draft rotate brick skill
btcli regen_hotkey --wallet.name alice --wallet.hotkey 66 --mnemonic midnight want pulse scrub bracket draft spend reward north clown screen whale
btcli regen_hotkey --wallet.name alice --wallet.hotkey 67 --mnemonic thumb proud best hurry cabbage page camera alone leaf decide student romance
btcli regen_hotkey --wallet.name alice --wallet.hotkey 68 --mnemonic absorb village input autumn castle praise gasp tank harsh push divide tobacco
btcli regen_hotkey --wallet.name alice --wallet.hotkey 69 --mnemonic onion ensure defy moon common range estate hurdle will final stairs flip
btcli regen_hotkey --wallet.name alice --wallet.hotkey 70 --mnemonic talent chalk mystery fit royal effort govern party corn surround usage injury
btcli regen_hotkey --wallet.name alice --wallet.hotkey 71 --mnemonic stick autumn boss member want rubber key tilt carpet limit flock wear
btcli regen_hotkey --wallet.name alice --wallet.hotkey 72 --mnemonic survey era dizzy elder first vague baby best science increase boost cart
btcli regen_hotkey --wallet.name alice --wallet.hotkey 73 --mnemonic rely gun duck jazz acquire faith kit hat zoo butter length spirit
btcli regen_hotkey --wallet.name alice --wallet.hotkey 74 --mnemonic manual tackle turkey discover alert come spring matter elite result object panel
btcli regen_hotkey --wallet.name alice --wallet.hotkey 75 --mnemonic history demise decorate print author wave casual movie someone erosion old whip
btcli regen_hotkey --wallet.name alice --wallet.hotkey 76 --mnemonic rough address wheat spike away million hair course spell float dignity brass
btcli regen_hotkey --wallet.name alice --wallet.hotkey 77 --mnemonic bounce library stay local skin lawn pave dust cousin vehicle screen morning
btcli regen_hotkey --wallet.name alice --wallet.hotkey 78 --mnemonic decade moon gold uphold pink hurt rabbit tone curious parrot crew broccoli
btcli regen_hotkey --wallet.name alice --wallet.hotkey 79 --mnemonic unable horn call puppy plunge mercy repeat coyote segment derive come track
btcli regen_hotkey --wallet.name alice --wallet.hotkey 80 --mnemonic blame model enforce share bronze panic obscure crime hazard island slush inmate
btcli regen_hotkey --wallet.name alice --wallet.hotkey 81 --mnemonic stomach luggage kid filter already rail either awful hazard segment grain more
btcli regen_hotkey --wallet.name alice --wallet.hotkey 82 --mnemonic chaos income muscle ginger soldier quote include steak polar vessel kiwi ignore
btcli regen_hotkey --wallet.name alice --wallet.hotkey 83 --mnemonic dilemma grief trap response video amateur safe debris clip diesel mutual raven
btcli regen_hotkey --wallet.name alice --wallet.hotkey 84 --mnemonic sponsor build shy lava nominee obey novel action jaguar upper manual harbor
btcli regen_hotkey --wallet.name alice --wallet.hotkey 85 --mnemonic vital length pilot favorite inflict tired buddy clean pass target during expire
btcli regen_hotkey --wallet.name alice --wallet.hotkey 86 --mnemonic solve glue chase magnet jewel oven garlic where message twin slush clean
btcli regen_hotkey --wallet.name alice --wallet.hotkey 87 --mnemonic now indoor fantasy emotion melody engine private wing inside city more early
btcli regen_hotkey --wallet.name alice --wallet.hotkey 88 --mnemonic grunt easily pioneer object carbon rapid master seminar energy hunt party dish
btcli regen_hotkey --wallet.name alice --wallet.hotkey 89 --mnemonic text patrol grass drop maximum barrel act reopen spring sting wild volume
btcli regen_hotkey --wallet.name alice --wallet.hotkey 90 --mnemonic term hello coach mercy hole repeat uphold because violin because together daring
btcli regen_hotkey --wallet.name alice --wallet.hotkey 91 --mnemonic orchard hammer glance guess analyst sentence muffin blouse fluid term swarm seat
btcli regen_hotkey --wallet.name alice --wallet.hotkey 92 --mnemonic course kid stomach cake idle hawk paper cube pupil code feel skull
btcli regen_hotkey --wallet.name alice --wallet.hotkey 93 --mnemonic cook sausage blanket toast debate ceiling nut glance service neck used reopen
btcli regen_hotkey --wallet.name alice --wallet.hotkey 94 --mnemonic east crunch toddler taxi reflect bid roof opinion victory junk lawsuit unique
btcli regen_hotkey --wallet.name alice --wallet.hotkey 95 --mnemonic force zone limb aspect ritual toilet exist diesel detail valve nature turn
btcli regen_hotkey --wallet.name alice --wallet.hotkey 96 --mnemonic crystal slight describe amount ladder stable push permit valid immune mushroom bamboo
btcli regen_hotkey --wallet.name alice --wallet.hotkey 97 --mnemonic wasp obey blush letter basic hire private warrior file sad orient admit
btcli regen_hotkey --wallet.name alice --wallet.hotkey 98 --mnemonic harvest story sign gift rail fatigue cancel dog detect glad autumn split
btcli regen_hotkey --wallet.name alice --wallet.hotkey 99 --mnemonic crop remove chuckle alley explain aspect electric exotic fall spawn define acid

for no in $(seq 0 99); 
    do btcli register --subtensor.network finney --netuid 1 --wallet.name alice --wallet.hotkey $no --cuda.TPB 512 --cuda.update_interval 800000 --cuda.dev_id 0 1 2 3 4 5 6 7 --cuda.use_cuda  --logging.debug --no_prompt;
done